---
build:
  nodes:
    analysis:
      image: node:20
      tests:
        override:
          - npm install
          - npm test

filter:
    paths:
        # Specify directories that Scrutinizer will analyze.
        - src/
    excluded_paths:
        - node_modules/
        - public/

checks:
  javascript: true