---
tools:
    eslint:
        enabled: true
    # Set to true if using external tools for code coverage.
    external_code_coverage: false
    # javascript_analyzer:
    #     enabled: true
    #     config:
    #         security_review: true
    #         duplicated_code: true

filter:
    paths:
        # Specify directories that Scrutinizer will analyze.
        - src/
    excluded_paths:
        - node_modules/
        - public/

# checks:
#     javascript:
#         no_param_assign: true
#         no_arguments_calls: true
#         no_alert: true

build:
    nodes:
        analysis:
            environment:
                node: 'iron'
                # npm: true
            dependencies:
                before:
                    - npm install
            tests:
                override:
                    - command: npm run test
                      coverage:
                        file: coverage/lcov.info
                        format: php-clover
                    - command: eslint .
                      # ignore_errors: true

# coding_style:
#     javascript:
#         spaces:
#             # Adjust indentation rules
#             indentation: 4  # Number of spaces for indentation
#         line_endings: "\n"  # Enforce UNIX line endings
#         max_line_length: 120  # Max line length per coding style
