---
build:
  nodes:
    analysis:
      image: node:20-bullseye
      environment:
        variables:
          NODE_VERSION: 20
      tests:
        override:
          - nvm use $NODE_VERSION
          - npm install
          - npm test

filter:
    paths:
        # Specify directories that Scrutinizer will analyze.
        - src/
    excluded_paths:
        - node_modules/
        - public/

checks:
  javascript: true